---
- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create pgadmin directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "5050"
    group: "5050"
  loop:
    - "/opt/pgadmin"
    - "{{ pgadmin_data_dir }}"
    - "{{ pgadmin_config_dir }}"

- name: Ensure traefik network exists
  shell: docker network create traefik || true

- name: Create pgAdmin servers configuration
  template:
    src: servers.json.j2
    dest: "{{ pgadmin_config_dir }}/servers.json"
    mode: "0644"

- name: Create pgadmin docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/pgadmin/docker-compose.yml
    mode: "0644"
  notify: restart pgadmin

- name: Start pgadmin using docker compose
  shell: |
    cd /opt/pgadmin
    docker compose up -d
  register: compose_result
  changed_when: "'Started' in compose_result.stderr or 'Creating' in compose_result.stderr"

- name: Wait for pgAdmin to be ready
  uri:
    url: "https://{{ pgadmin_domain }}"
    method: GET
    timeout: 10
    validate_certs: no
  register: pgadmin_web_check
  retries: 5
  delay: 5
  until: pgadmin_web_check.status == 200
  failed_when: false
  changed_when: false

- name: Display pgAdmin access information
  debug:
    msg:
      - "pgAdmin is now running!"
      - "Access it at: https://{{ pgadmin_domain }}"
      - "Login email: {{ pgadmin_email }}"
      - ""
      - "Pre-configured PostgreSQL server:"
      - "  Host: {{ postgresql_host_ip }}"
      - "  Port: {{ postgresql_port }}"
      - "  Username: {{ postgresql_username }}"
