---
- name: verify docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: verify docker compose installation
  command: docker compose version
  register: compose_version
  changed_when: false

- name: display docker versions
  debug:
    msg:
      - "Docker: {{ docker_version.stdout }}"
      - "Docker Compose: {{ compose_version.stdout }}"
