---
- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
  become: yes
  notify:
    - verify docker installation
    - verify docker compose installation
    - display docker versions
